### ISSUE TITLE
Mapbender Session WMC not written after initialization of WMC / MobileMap opens without layers switching viewer

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#26] opened 2021-05-25 12:43 UTC
### Describe the bug ###

When loading a WMC document to a mapbender native map viewer GUI and switching the viewer to mobile there is no map.

### To Reproduce ###

1. Go to a GeoPortal instance (e.g. [geoportal.saarland](https://geoportal.saarland.de/))
1. Click on Map collections
1. Load in an arbritrary WMC document
1. Switch viewer to mobile without causing the WMC causing to update (e.g. moving the extent).
1. See error in empty map container

### Expected behavior ###

The current WMC should be transfered as it is rendered in the Browser.

## Additional context ##

The current WMC seems not to be written after loading the WMC from the database. Therefor mobilemap2 has nothing to load. If you move the map the current WMC is saved and the functionality is as expected.

**Comment by SvenTUM** [comment] 2022-05-25 10:40
I've heard this issue is supposed to be fixed. It seems to be fixed on geoportal.rlp.de.

The issue is still open and I have no intel on which commits / merges are related to the issue.
In our instance the issue is not solved after merging. 

@armin11 
Do you have any more information regarding this issue?
I've searched for commits from _Sebastian Pauli_, didn't find any. 
However you did this commit and mentioned him: d9b711a18b239b6b0d9ece2cf4727bb1270e38f8

We still have #17 unsolved on our system, that might be the reason why it's still not working for us.

**Comment by SvenTUM** [comment] 2022-05-25 14:23
I tried removing some of the differences in the JS files in https://github.com/LVGL-SL/mapbender-sl/commit/d3cc0536ef71853fcb4e2136af241922bd75396a yet that didn't seem to help. 

In our system the mobile client is opened in a new tab. If I search and load another service into the map the base map suddenly appears, yet it does not contain the WMC from the previous GUI.

**Closed** 2023-01-27 11:28 UTC
Labels: bug
